fix

diff --git a/run_via_ssh b/run_via_ssh
--- a/run_via_ssh
+++ b/run_via_ssh
@@ -6,16 +6,16 @@ SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 
 for i in {1..10}; do
   TEMP_DIR=$(ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} <<EOF
-  TEMP_DIR=\$(mktemp -d)
-  if [ -z "\$TEMP_DIR" ]; then
-    echo 'Failed to create temporary directory' >&2
-    exit 1
-  else
-    echo \$TEMP_DIR
-    mkdir \$TEMP_DIR/build
-  fi
-EOF
-) && break || sleep 1
+    TEMP_DIR=$(mktemp -d)
+    if [ -z "$TEMP_DIR" ]; then
+      echo 'Failed to create temporary directory' >&2
+      exit 1
+    else
+      echo $TEMP_DIR
+      mkdir $TEMP_DIR/build
+    fi
+  EOF
+  ) && break || sleep 1
 done
 
 for i in {1..10}; do
