Fix in run_via_ssh (#4)

diff --git a/run_via_ssh b/run_via_ssh
--- a/run_via_ssh
+++ b/run_via_ssh
@@ -17,17 +17,34 @@ done
 
 echo "Copied package to $TEMP_DIR"
 
-for n in `seq 1 10`; do
-  ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} <<EOF
+cat <<EOF > /tmp/script
 cd ${TEMP_DIR}
 curl -sSL "https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/main/upload_repo_${TYPE}" > script
 chmod +x script
-ls -la
 DISTRO="${DISTR}" DIGIT_DELIMITER2="${DELIMITER}" ./script
+echo "Script finished with exit code $?"
 echo "Removing ${TEMP_DIR}"
 rm -rf ${TEMP_DIR}
 echo "Cleaning up old temp dirs in /tmp/"
 find /tmp -type d -ctime +2 -name 'tmp.*' -exec rm -rf {} \;
 EOF
-  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: couldn't run script via ssh" && exit 1; fi;
+chmod +x /tmp/script
+
+script_name="/tmp/script$RANDOM"
+for n in `seq 1 10`; do
+  scp -i ${SSH_KEY_LOCATION} ${SSH_OPTS} /tmp/script ${REMOTE_SERVER}:${script_name}
+  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: scp failed" && exit 1; fi;
 done
+echo "Copied script to ${REMOTE_SERVER}:${script_name}"
+
+for n in `seq 1 10`; do
+  ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} ${script_name}
+  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: script failed via ssh" && exit 1; fi;
+done
+echo "Ran ${script_name} on ${REMOTE_SERVER}"
+
+for n in `seq 1 10`; do
+  ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} rm ${script_name}
+  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: failed to cleanup via ssh" && exit 1; fi;
+done
+echo "Cleanup of ${script_name} finished"
