Output redirect

diff --git a/run_via_ssh b/run_via_ssh
--- a/run_via_ssh
+++ b/run_via_ssh
@@ -142,8 +142,8 @@ cat <<EOF > /tmp/script
 echo "Starting remote script execution"
 cd "${TEMP_DIR}" || { echo "Failed to cd to ${TEMP_DIR}"; exit 1; }
 
-echo "Downloading https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/feat/improve-output/upload_repo_${TYPE} to script"
-curl -sSL "https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/feat/improve-output/upload_repo_${TYPE}" > script || { echo "Failed to download upload_repo_${TYPE}"; exit 1; }
+echo "Downloading https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/main/upload_repo_${TYPE} to script"
+curl -sSL "https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/main/upload_repo_${TYPE}" > script || { echo "Failed to download upload_repo_${TYPE}"; exit 1; }
 chmod +x script
 echo "Running upload_repo_${TYPE} script"
 DISTRO="${DISTR}" DIGIT_DELIMITER2="${DELIMITER}" TARGET="${TARGET}" DRY_RUN="${DRY_RUN}" ./script
