Update upload_repo_deb

diff --git a/upload_repo_deb b/upload_repo_deb
--- a/upload_repo_deb
+++ b/upload_repo_deb
@@ -131,6 +131,6 @@ done
 
 echo "Cleanup"
 echo "BUILD_FOLDER is $BUILD_FOLDER"
-ls -la "$BUILD_FOLDER"*deb || echo "Failed to ls"
+#ls -la "$BUILD_FOLDER"*deb || echo "Failed to ls"
 rm -rf "$BUILD_FOLDER"*deb || echo "Failed to cleanup"
 echo "Cleanup complete"
