fix

diff --git a/upload_repo_rpm b/upload_repo_rpm
--- a/upload_repo_rpm
+++ b/upload_repo_rpm
@@ -38,7 +38,7 @@ repo_generator() {
   echo $command
   if [ -z "$DRY_RUN" ]; then
     eval $command
-    [[ ! $? -eq 0 ]] && exit 1
+    [[ ! $? -eq 0 ]] && echo "ERROR: command failed" && exit 1
   fi
 }
 
