Update upload_repo_deb

diff --git a/upload_repo_deb b/upload_repo_deb
--- a/upload_repo_deb
+++ b/upload_repo_deb
@@ -34,10 +34,10 @@ repo_generator() {
   command="/usr/bin/docker exec -i repo-generator echo ----------- $@ ---------------"
 
   echo "Command to run: $command"
-  if [ -z "$DRY_RUN" ]; then
-    eval "$command"
-    if [[ ! $? -eq 0 ]]; then echo "ERROR: command failed"; exit 1; fi
-  fi
+#  if [ -z "$DRY_RUN" ]; then
+#    eval "$command"
+#    if [[ ! $? -eq 0 ]]; then echo "ERROR: command failed"; exit 1; fi
+#  fi
 }
 
 echo "Contents of ./$BUILD_FOLDER:"
@@ -143,6 +143,6 @@ find "$BUILD_FOLDER"
 
 echo "Cleanup"
 echo "BUILD_FOLDER is $BUILD_FOLDER"
-#ls -la $BUILD_FOLDER/ || echo "Failed to ls"
-#rm -rf $BUILD_FOLDER/* || echo "Failed to cleanup"
+ls -la $BUILD_FOLDER/ || echo "Failed to ls"
+rm -rf $BUILD_FOLDER/* || echo "Failed to cleanup"
 echo "Cleanup complete"
