Update upload_repo_deb

diff --git a/upload_repo_deb b/upload_repo_deb
--- a/upload_repo_deb
+++ b/upload_repo_deb
@@ -143,6 +143,6 @@ find "$BUILD_FOLDER"
 
 echo "Cleanup"
 echo "BUILD_FOLDER is $BUILD_FOLDER"
-#ls -la "$BUILD_FOLDER"*deb || echo "Failed to ls"
-rm -rf "$BUILD_FOLDER"*deb || echo "Failed to cleanup"
+ls -la $BUILD_FOLDER/ || echo "Failed to ls"
+rm -rf $BUILD_FOLDER/* || echo "Failed to cleanup"
 echo "Cleanup complete"
