Packages integrity check

diff --git a/upload_repo_deb b/upload_repo_deb
--- a/upload_repo_deb
+++ b/upload_repo_deb
@@ -40,6 +40,15 @@ repo_generator() {
 
 declare -A archs
 
+echo "Packages integrity check"
+for f in "$BUILD_FOLDER"*deb; do
+  packageName="$(basename "$f")"
+  if ! repo_generator --distro "$DISTRO" --check-package --name "$packageName" "<$f"; then
+      echo "$packageName is corrupted. Abort uploading"
+      exit 1
+  fi
+done
+
 for f in "$BUILD_FOLDER"*deb; do
   echo "file $f"
   packageName="$(basename "$f")"
diff --git a/upload_repo_rpm b/upload_repo_rpm
--- a/upload_repo_rpm
+++ b/upload_repo_rpm
@@ -44,6 +44,16 @@ repo_generator() {
 
 declare -A archs
 
+
+echo "Packages integrity check"
+for f in $(eval echo $BUILD_FOLDER$FILE_MASK); do
+  packageName="$(basename "$f")"
+  if ! repo_generator -n "$packageName" -d centos --check-package "<$f"; then
+      echo "$packageName is corrupted. Abort uploading"
+      exit 1
+  fi
+done
+
 for f in $(eval echo $BUILD_FOLDER$FILE_MASK); do
 
   echo "file $f"
