Update upload_repo_deb

diff --git a/upload_repo_deb b/upload_repo_deb
--- a/upload_repo_deb
+++ b/upload_repo_deb
@@ -30,11 +30,8 @@ set -e
 
 repo_generator() {
   # shellcheck disable=SC2068
-#  command="/usr/bin/docker exec -i repo-generator /generator.sh $@"
-  command="/usr/bin/docker exec -i repo-generator echo ----------- $@ ---------------"
-#  command="echo ----------- $@ ---------------"
-
-  echo "Command to run: $command"
+  command="/usr/bin/docker exec -i repo-generator /generator.sh $@"
+  echo "$command"
   if [ -z "$DRY_RUN" ]; then
     eval "$command"
     if [[ ! $? -eq 0 ]]; then echo "ERROR: command failed"; exit 1; fi
@@ -54,9 +51,6 @@ for f in `find "$BUILD_FOLDER" -type f \( -name "*deb" \)`; do
       exit 1
   fi
 done
-
-echo "Contents of ./$BUILD_FOLDER:"
-find "$BUILD_FOLDER"
 
 for f in `find "$BUILD_FOLDER" -type f \( -name "*deb" \)`; do
   echo "file $f"
@@ -107,9 +101,6 @@ for f in `find "$BUILD_FOLDER" -type f \( -name "*deb" \)`; do
   fi
 done
 
-echo "Contents of ./$BUILD_FOLDER:"
-find "$BUILD_FOLDER"
-
 echo "Finished putting packages"
 
 if [ -n "$MAKE_BUNDLE" ]; then
@@ -130,20 +121,12 @@ if [ -n "$MAKE_BUNDLE" ]; then
   fi
 fi
 
-echo "Contents of ./$BUILD_FOLDER:"
-find "$BUILD_FOLDER"
-
 echo "Indexing"
 for arch in "${!archs[@]}"; do
   echo "Indexing $DISTRO $arch $TARGET"
   repo_generator --distro "$DISTRO" --architecture "$arch" --target "$TARGET" --only-index
 done
 
-echo "Contents of ./$BUILD_FOLDER:"
-find "$BUILD_FOLDER"
-
 echo "Cleanup"
-echo "BUILD_FOLDER is $BUILD_FOLDER"
-ls -la $BUILD_FOLDER/ || echo "Failed to ls"
-rm -rf $BUILD_FOLDER/* || echo "Failed to cleanup"
+rm -rf "$BUILD_FOLDER"*deb || echo "Failed to cleanup"
 echo "Cleanup complete"
